# Generated by Django 5.2.1 on 2025-10-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Receivables', 'Receivables'), ('Payables', 'Payables'), ('Equity Capital', 'Equity Capital'), ('Inventory', 'Inventory'), ('Prepaid Expenses', 'Prepaid Expenses'), ('Fixed Assets', 'Fixed Assets'), ('Investments', 'Investments'), ('Accrued Expenses', 'Accrued Expenses'), ('Unearned Revenue', 'Unearned Revenue'), ('Loans Payable', 'Loans Payable'), ('Retained Earnings', 'Retained Earnings'), ('Owner’s Draw', 'Owner’s Draw'), ('Sales Revenue', 'Sales Revenue'), ('Service Income', 'Service Income'), ('Interest Income', 'Interest Income'), ('Rent Expense', 'Rent Expense'), ('Utilities Expense', 'Utilities Expense'), ('Salaries Expense', 'Salaries Expense'), ('Office Supplies', 'Office Supplies'), ('Depreciation Expense', 'Depreciation Expense')], default='Cash', max_length=100)),
                ('account_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], default='ASSET', max_length=20)),
                ('account_description', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('BDT', 'Bangladeshi Taka'), ('EUR', 'Euro'), ('INR', 'Indian Rupee'), ('GBP', 'British Pound')], default='USD', max_length=10)),
                ('cost_center', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Not Active')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
