# Generated by Django 5.2.1 on 2025-10-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('construction', 'Construction'), ('salesmarketing', 'Sales & Marketing'), ('finance', 'Finance')], help_text='Assigned department based on Azure AD email mapping', max_length=50, null=True),
        ),
    ]
