# Generated by Django 5.2.1 on 2025-10-28 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerdetailed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_company', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, choices=[('organic', 'Organic Search'), ('paid_ads', 'Paid Ads'), ('social', 'Social Media'), ('email', 'Email Campaign'), ('referral', 'Referral'), ('event', 'Event/Trade Show'), ('website', 'Website Form'), ('cold', 'Cold Call/Email'), ('affiliate', 'Affiliate Marketing'), ('content', 'Content Marketing'), ('sms', 'SMS Campaign'), ('chatbot', 'Chatbot Interaction'), ('partner', 'Channel Partner'), ('retargeting', 'Retargeting Campaign'), ('video', 'Video Marketing'), ('inbound_call', 'Inbound Call'), ('outbound_call', 'Outbound Call'), ('direct_mail', 'Direct Mail'), ('app', 'Mobile App'), ('demo', 'Product Demo'), ('survey', 'Survey Response'), ('linkedin', 'LinkedIn Outreach'), ('youtube', 'YouTube Channel'), ('podcast', 'Podcast Mention'), ('forum', 'Online Forum or Community')], max_length=30)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('rejected', 'Rejected')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_customer_name', to='customerdetailed.customerdetailed', verbose_name='Customer Name')),
            ],
        ),
    ]
